FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY pyproject.toml .
RUN pip install --no-cache-dir '.[dev]'

COPY . /app

EXPOSE 8000

ENTRYPOINT ["./run_app.sh"]
