# Generated by Django 6.0.4 on 2026-04-16 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('fingerprint', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_cfg_interval', models.IntegerField()),
                ('activate_pump_interval', models.IntegerField()),
                ('read_sensors_interval', models.IntegerField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='app.device')),
            ],
            options={
                'db_table': 'device_cfg',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='cfg_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='app.deviceconfiguration'),
        ),
    ]
