# Generated by Django 6.0.4 on 2026-04-18 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('check_cfg_interval', models.IntegerField()),
                ('activate_pump_interval', models.IntegerField()),
                ('read_sensors_interval', models.IntegerField()),
                ('cfg_hash', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'db_table': 'device_cfg',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('model', models.TextField()),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('cfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='app.deviceconfiguration')),
            ],
            options={
                'db_table': 'device',
            },
        ),
    ]
